/**
 * 🎯 Pipeline Orchestrator — dispatches to individual agent services
 *
 * This is the single entry point for running pipeline steps.
 * Each agent is a separate module that can be tested/reused independently.
 */

import { runAssembly } from './assembly.agent';
import { runImageGen } from './image-gen.agent';
import { persistUpdate } from './run-persistence';
import { completeRun, createRun, failRun, findReusableRun, getRun } from './run-tracker';
import { runScriptWriter } from './script-writer.agent';
import { runStoryboard } from './storyboard.agent';
import type { GenerateRequest } from './types';
import { runVoiceover } from './voiceover.agent';

/** Prevent concurrent reuse of the same run (race-condition guard) */
const lockedRuns = new Set<string>();

const STEP_LABELS: Record<string, string> = {
  scriptWriter: '✍️ Running Script Writer...',
  storyboard: '🎬 Running Storyboard Generator...',
  imageGen: '🖼️ Running Image Generation...',
  voiceover: '🎤 Running Voice Producer...',
  assembly: '🎥 Running Video Assembly...',
};

/** Determine which steps to run based on request */
function resolveSteps(req: GenerateRequest): string[] {
  const steps: string[] = [];
  if (!req.storyboardOnly) steps.push('scriptWriter');
  if (!req.scriptOnly) steps.push('storyboard');
  if (req.imageGenEnabled) steps.push('imageGen');
  if (req.voiceoverEnabled) steps.push('voiceover');
  if ((req as Record<string, unknown>).assemblyEnabled) steps.push('assembly');
  return steps;
}

/** Execute a single step — returns true if successful */
async function executeStep(step: string, runId: string, req: GenerateRequest): Promise<boolean> {
  const run = getRun(runId);
  if (!run) return false;

  // Skip storyboard if script writer already produced it (full-pipeline mode)
  if (step === 'storyboard') {
    const storyboardJson = run.result?.files?.['storyboard.json'] as
      | { scenes?: unknown[] }
      | undefined;
    if (storyboardJson?.scenes && (storyboardJson.scenes as unknown[]).length > 0) {
      run.logs.push({
        t: Date.now(),
        level: 'info',
        msg: '⏭️ Storyboard already generated by Script Writer — skipping',
        step: 'storyboard',
      });
      if (!run.completedSteps) run.completedSteps = [];
      if (!run.completedSteps.includes(step)) run.completedSteps.push(step);
      return true;
    }
  }

  run.logs.push({
    t: Date.now(),
    level: 'info',
    msg: STEP_LABELS[step] || `🔧 Running ${step}...`,
    step,
  });

  switch (step) {
    case 'scriptWriter':
      await runScriptWriter(runId, req);
      break;
    case 'storyboard':
      await runStoryboard(runId, req);
      break;
    case 'imageGen':
      await runImageGen(runId, req);
      break;
    case 'voiceover':
      await runVoiceover(runId, req);
      break;
    case 'assembly':
      await runAssembly(runId, req);
      break;
    default:
      failRun(run, `Step "${step}" chưa có API endpoint riêng. Cần deploy full pipeline.`);
      return false;
  }

  if (run.status === 'failed') return false;

  // Track completed step
  if (!run.completedSteps) run.completedSteps = [];
  if (!run.completedSteps.includes(step)) run.completedSteps.push(step);

  return true;
}

/** Run the full pipeline — chains enabled steps sequentially */
export async function generate(
  req: GenerateRequest
): Promise<{ success: boolean; runId: string; message: string }> {
  const steps = resolveSteps(req);
  const topic = req.topic || req.transcript;

  // Reuse a recent completed run for the same channel+topic so re-runs are grouped
  const reusable = findReusableRun(req.channelId, topic);
  let runId: string;
  let run;

  if (reusable && !lockedRuns.has(reusable.id) && reusable.channelId === req.channelId) {
    runId = reusable.id;
    lockedRuns.add(runId);
    run = reusable;
    run.status = 'running';
    run.startedAt = new Date().toISOString();
    run.error = undefined;
    run.completedAt = undefined;
    run.durationMs = undefined;
    run.pipelineSteps = steps;
    run.completedSteps = [];
    run.logs = run.logs.filter((l) => l.level !== 'error' && l.level !== 'warn');
    run.logs.push({ t: Date.now(), level: 'info', msg: '🔄 Re-running full pipeline...' });
    persistUpdate(run).catch(() => {});
  } else {
    runId = `gen_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
    lockedRuns.add(runId);
    run = createRun(runId, req, '🚀 Starting full pipeline...');
  }

  // Run steps sequentially in background
  (async () => {
    try {
      for (const step of steps) {
        const ok = await executeStep(step, runId, req);
        if (!ok) return;
      }

      if (run.status === 'running') {
        completeRun(run, run.result || { outputDir: 'remote', files: {} });
      }
    } catch (err: unknown) {
      failRun(run, err instanceof Error ? err.message : String(err));
    } finally {
      lockedRuns.delete(runId);
    }
  })();

  return { success: true, runId, message: `Pipeline started: ${steps.join(' → ')}` };
}

/** Run a single pipeline step — reuses a recent run for the same channel+topic if available */
export async function generateStep(
  step: string,
  req: GenerateRequest
): Promise<{ success: boolean; runId: string; message: string }> {
  const label = STEP_LABELS[step] || `🔧 Running ${step}...`;
  const topic = req.topic || req.transcript;

  // Reuse a recent completed run for the same channel+topic so steps are grouped
  const reusable = findReusableRun(req.channelId, topic);
  let runId: string;
  let run;

  if (reusable && !lockedRuns.has(reusable.id) && reusable.channelId === req.channelId) {
    runId = reusable.id;
    lockedRuns.add(runId);
    run = reusable;
    run.status = 'running';
    run.startedAt = new Date().toISOString();
    run.error = undefined;
    run.completedAt = undefined;
    run.durationMs = undefined;
    run.pipelineSteps = [...new Set([...(run.pipelineSteps || []), step])];
    // Clear old error/warn logs from previous failed attempts to avoid stale messages
    run.logs = run.logs.filter((l) => l.level !== 'error' && l.level !== 'warn');
    run.logs.push({ t: Date.now(), level: 'info', msg: `🔄 Appending step: ${label}`, step });
    persistUpdate(run).catch(() => {});
  } else {
    runId = `run_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`;
    lockedRuns.add(runId);
    run = createRun(runId, req, label);
    run.pipelineSteps = [step];
    run.completedSteps = [];
  }

  // Run in background, then finalize
  (async () => {
    try {
      const ok = await executeStep(step, runId, req);
      if (!ok) return;
      // Finalize: agents save result via saveStepResult, orchestrator marks complete
      if (run.status === 'running') {
        completeRun(run, run.result || { outputDir: 'remote', files: {} });
      }
    } catch (err: unknown) {
      failRun(run, err instanceof Error ? err.message : String(err));
    } finally {
      lockedRuns.delete(runId);
    }
  })();

  return { success: true, runId, message: label };
}

/** Resume an interrupted pipeline run — skip already-completed steps */
export async function resumeRun(
  runId: string
): Promise<{ success: boolean; runId: string; message: string }> {
  const run = getRun(runId);
  if (!run) {
    return { success: false, runId, message: 'Run not found in memory' };
  }
  if (run.status !== 'interrupted' && run.status !== 'failed') {
    return { success: false, runId, message: `Cannot resume run with status "${run.status}"` };
  }
  if (lockedRuns.has(runId)) {
    return { success: false, runId, message: 'Run is already being processed' };
  }
  lockedRuns.add(runId);

  const allSteps = run.pipelineSteps || resolveSteps(run.input);
  const done = new Set(run.completedSteps || []);
  const remaining = allSteps.filter((s) => !done.has(s));

  if (remaining.length === 0) {
    // All steps were done — just mark complete
    completeRun(run, run.result || { outputDir: 'remote', files: {} });
    return { success: true, runId, message: 'All steps already completed — marking done.' };
  }

  // Reset run state for resumption
  run.status = 'running';
  run.startedAt = new Date().toISOString();
  run.error = undefined;
  run.completedAt = undefined;
  run.durationMs = undefined;
  run.logs.push({
    t: Date.now(),
    level: 'info',
    msg: `🔄 Resuming pipeline from ${STEP_LABELS[remaining[0]] || remaining[0]}... (${done.size}/${allSteps.length} steps done)`,
    step: remaining[0],
  });
  persistUpdate(run).catch(() => {});

  // Run remaining steps in background
  (async () => {
    try {
      for (const step of remaining) {
        const ok = await executeStep(step, runId, run.input);
        if (!ok) return;
      }
      if (run.status === 'running') {
        completeRun(run, run.result || { outputDir: 'remote', files: {} });
      }
    } catch (err: unknown) {
      failRun(run, err instanceof Error ? err.message : String(err));
    } finally {
      lockedRuns.delete(runId);
    }
  })();

  return {
    success: true,
    runId,
    message: `Resuming: ${remaining.join(' → ')} (skipped ${done.size} completed step${done.size > 1 ? 's' : ''})`,
  };
}
