#!/usr/bin/env node

/**
 * N8N MCP Setup Script
 * 
 * Automatically configures n8n MCP servers for VS Code
 * Run: npm run setup:mcp-n8n
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectRoot = path.resolve(__dirname, '..');

// Colors for console output
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  red: '\x1b[31m',
  cyan: '\x1b[36m',
};

const log = {
  info: (msg) => console.log(`${colors.blue}ℹ${colors.reset} ${msg}`),
  success: (msg) => console.log(`${colors.green}✓${colors.reset} ${msg}`),
  warn: (msg) => console.log(`${colors.yellow}⚠${colors.reset} ${msg}`),
  error: (msg) => console.log(`${colors.red}✗${colors.reset} ${msg}`),
  header: (msg) => console.log(`\n${colors.bright}${colors.cyan}${msg}${colors.reset}\n`),
};

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query) {
  return new Promise((resolve) => rl.question(query, resolve));
}

async function main() {
  log.header('🔌 N8N MCP Setup Wizard');
  console.log('This script will configure n8n MCP servers for VS Code.\n');

  // Step 1: Check if n8n MCP packages are installed
  log.info('Checking MCP packages...');
  
  try {
    execSync('npx mcp-n8n --version', { stdio: 'ignore' });
    log.success('mcp-n8n is available');
  } catch {
    log.warn('Installing mcp-n8n...');
    execSync('npm install -g mcp-n8n', { stdio: 'inherit' });
    log.success('mcp-n8n installed');
  }

  try {
    execSync('npx @leonardsellem/n8n-mcp-server --version', { stdio: 'ignore' });
    log.success('@leonardsellem/n8n-mcp-server is available');
  } catch {
    log.warn('Installing @leonardsellem/n8n-mcp-server...');
    execSync('npm install -g @leonardsellem/n8n-mcp-server', { stdio: 'inherit' });
    log.success('@leonardsellem/n8n-mcp-server installed');
  }

  // Step 2: Get n8n configuration
  log.header('📝 N8N Configuration');
  
  const n8nUrl = await question('N8N Base URL [http://localhost:5678]: ') || 'http://localhost:5678';
  const n8nApiKey = await question('N8N API Key (from Settings → n8n API): ');

  if (!n8nApiKey) {
    log.error('API Key is required! Generate one from n8n Settings → n8n API');
    log.info('Then run this script again.');
    rl.close();
    process.exit(1);
  }

  // Optional webhook config
  const useWebhooks = await question('Configure webhook authentication? (y/N): ');
  let webhookUser = '';
  let webhookPass = '';
  
  if (useWebhooks.toLowerCase() === 'y') {
    webhookUser = await question('Webhook Username: ');
    webhookPass = await question('Webhook Password: ');
  }

  // Step 3: Create/Update .env.mcp file
  log.header('📁 Creating Configuration Files');

  const envContent = `# N8N MCP Configuration
# Generated by setup:mcp-n8n on ${new Date().toISOString()}

N8N_BASE_URL=${n8nUrl}
N8N_API_URL=${n8nUrl}/api/v1
N8N_API_KEY=${n8nApiKey}
${webhookUser ? `N8N_WEBHOOK_USERNAME=${webhookUser}` : '# N8N_WEBHOOK_USERNAME='}
${webhookPass ? `N8N_WEBHOOK_PASSWORD=${webhookPass}` : '# N8N_WEBHOOK_PASSWORD='}
DEBUG=false
`;

  const envPath = path.join(projectRoot, '.env.mcp');
  fs.writeFileSync(envPath, envContent);
  log.success(`Created ${envPath}`);

  // Step 4: Update .vscode/mcp.json
  const mcpConfigPath = path.join(projectRoot, '.vscode', 'mcp.json');
  const mcpConfig = {
    mcpServers: {
      n8n: {
        command: 'npx',
        args: ['-y', 'mcp-n8n'],
        env: {
          N8N_BASE_URL: n8nUrl,
          N8N_API_KEY: n8nApiKey,
        },
        disabled: false,
      },
      'n8n-advanced': {
        command: 'npx',
        args: ['-y', '@leonardsellem/n8n-mcp-server'],
        env: {
          N8N_API_URL: `${n8nUrl}/api/v1`,
          N8N_API_KEY: n8nApiKey,
          ...(webhookUser && { N8N_WEBHOOK_USERNAME: webhookUser }),
          ...(webhookPass && { N8N_WEBHOOK_PASSWORD: webhookPass }),
          DEBUG: 'false',
        },
        disabled: false,
      },
      filesystem: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-filesystem', 'D:/0.PROJECTS'],
        disabled: false,
      },
    },
  };

  fs.writeFileSync(mcpConfigPath, JSON.stringify(mcpConfig, null, 2));
  log.success(`Updated ${mcpConfigPath}`);

  // Step 5: Set environment variables (Windows)
  log.header('🔐 Setting Environment Variables');
  
  const setEnvVars = await question('Set system environment variables? (Y/n): ');
  
  if (setEnvVars.toLowerCase() !== 'n') {
    try {
      execSync(`setx N8N_BASE_URL "${n8nUrl}"`, { stdio: 'ignore' });
      execSync(`setx N8N_API_URL "${n8nUrl}/api/v1"`, { stdio: 'ignore' });
      execSync(`setx N8N_API_KEY "${n8nApiKey}"`, { stdio: 'ignore' });
      log.success('Environment variables set (User scope)');
      log.warn('You need to restart VS Code for changes to take effect.');
    } catch (error) {
      log.error('Failed to set environment variables. Please set manually:');
      console.log(`  N8N_BASE_URL=${n8nUrl}`);
      console.log(`  N8N_API_URL=${n8nUrl}/api/v1`);
      console.log(`  N8N_API_KEY=${n8nApiKey}`);
    }
  }

  // Step 6: Test connection
  log.header('🧪 Testing Connection');
  
  try {
    const response = await fetch(`${n8nUrl}/api/v1/workflows`, {
      headers: {
        'X-N8N-API-KEY': n8nApiKey,
      },
    });
    
    if (response.ok) {
      const data = await response.json();
      log.success(`Connected to n8n! Found ${data.data?.length || 0} workflows.`);
    } else {
      log.warn(`Connection warning: ${response.status} ${response.statusText}`);
    }
  } catch (error) {
    log.warn(`Could not connect to n8n at ${n8nUrl}`);
    log.info('Make sure n8n is running before using MCP tools.');
  }

  // Summary
  log.header('✅ Setup Complete!');
  console.log('Next steps:');
  console.log('  1. Restart VS Code');
  console.log('  2. Open Copilot Chat (Ctrl+Shift+I)');
  console.log('  3. Test: @n8n Show me all workflows\n');
  console.log('Documentation: See N8N_MCP_SETUP.md for more details.\n');

  rl.close();
}

main().catch((error) => {
  log.error(`Setup failed: ${error.message}`);
  rl.close();
  process.exit(1);
});
