import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { FileText, Mail, Share2, BarChart, Clock, Calendar, AlertCircle, Eye } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { formatDistanceToNow } from 'date-fns';
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';
import { ContentReviewModal } from './ContentReviewModal';
import type { ContentQueue } from '@/types/automation';

interface ContentQueueListProps {
  items: (ContentQueue & { ai_agents?: { name: string; type: string } })[];
  isLoading?: boolean;
  onUpdate?: () => void;
}

const contentIcons: Record<string, any> = {
  blog_post: FileText,
  email: Mail,
  social_post: Share2,
  report: BarChart,
};

const statusColors: Record<string, string> = {
  pending: 'secondary',
  processing: 'default',
  published: 'outline',
  failed: 'destructive',
  scheduled: 'default',
};

export const ContentQueueList = ({ items, isLoading, onUpdate }: ContentQueueListProps) => {
  const navigate = useNavigate();
  const [selectedContent, setSelectedContent] = useState<any>(null);
  const [reviewModalOpen, setReviewModalOpen] = useState(false);

  const handleReview = (item: any, e: React.MouseEvent) => {
    e.stopPropagation();
    setSelectedContent(item);
    setReviewModalOpen(true);
  };

  if (isLoading) {
    return (
      <Card>
        <CardContent className="p-6">
          <div className="space-y-4">
            {[1, 2, 3].map((i) => (
              <Skeleton key={i} className="h-20 w-full" />
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!items || items.length === 0) {
    return (
      <Card>
        <CardContent className="p-12 text-center">
          <div className="flex flex-col items-center gap-4">
            <div className="p-4 bg-muted rounded-full">
              <FileText className="w-8 h-8 text-muted-foreground" />
            </div>
            <div>
              <h3 className="text-lg font-semibold mb-2">No Content in Queue</h3>
              <p className="text-muted-foreground">
                Content generated by agents will appear here
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardContent className="p-6">
        <div className="space-y-4">
          {items.map((item) => {
            const Icon = contentIcons[item.content_type] || FileText;
            const statusColor = statusColors[item.status] || 'secondary';

            return (
              <div
                key={item.id}
                className="flex items-center justify-between p-4 rounded-lg border bg-card hover:bg-accent/50 transition-colors cursor-pointer"
                onClick={() => navigate(`/automation/content/${item.id}`)}
              >
                <div className="flex items-center gap-4 flex-1">
                  <div className="p-2 bg-primary/10 rounded-lg">
                    <Icon className="w-5 h-5 text-primary" />
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <h4 className="font-semibold">
                        {item.title || 'Untitled Content'}
                      </h4>
                      <Badge variant={statusColor as any} className="capitalize">
                        {item.status}
                      </Badge>
                    </div>
                    <div className="flex items-center gap-4 text-sm text-muted-foreground">
                      <span className="capitalize">
                        {item.content_type.replace('_', ' ')}
                      </span>
                      {item.ai_agents && (
                        <>
                          <span>•</span>
                          <span>{item.ai_agents.name}</span>
                        </>
                      )}
                      {item.scheduled_for && (
                        <>
                          <span>•</span>
                          <span className="flex items-center gap-1">
                            <Calendar className="w-3 h-3" />
                            Scheduled for {formatDistanceToNow(new Date(item.scheduled_for), { addSuffix: true })}
                          </span>
                        </>
                      )}
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-4">
                  <div className="text-right">
                    <div className="text-xs text-muted-foreground flex items-center gap-1 justify-end">
                      <Clock className="w-3 h-3" />
                      {formatDistanceToNow(new Date(item.created_at), { addSuffix: true })}
                    </div>
                    <div className="text-xs font-medium mt-1">
                      Priority: {item.priority}/10
                    </div>
                  </div>
                  {item.status === 'pending' && (
                    <Button
                      variant="default"
                      size="sm"
                      onClick={(e) => handleReview(item, e)}
                    >
                      <Eye className="w-4 h-4 mr-1" />
                      Review
                    </Button>
                  )}
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation();
                      navigate(`/automation/content/${item.id}`);
                    }}
                  >
                    View
                  </Button>
                </div>
              </div>
            );
          })}
        </div>

        {/* Review Modal */}
        <ContentReviewModal
          open={reviewModalOpen}
          onOpenChange={setReviewModalOpen}
          content={selectedContent}
          onUpdate={() => {
            if (onUpdate) onUpdate();
            setReviewModalOpen(false);
          }}
        />

        {items.length >= 10 && (
          <div className="mt-4 text-center">
            <Button
              variant="ghost"
              onClick={() => navigate('/automation/content-queue')}
            >
              View All Content
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  );
};
