/**
 * Channel Config: Đứng Dậy Đi
 * Input type: Markdown chapters (pre-generated by AI pipeline)
 * Style: Dark cinematic noir duality — chiaroscuro, gritty urban
 */
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const KNOWLEDGE_DIR = join(__dirname, '..', '..', '..', 'knowledge');

export default {
  channelId: 'dungdaydi',
  channelName: 'Đứng Dậy Đi',
  author: 'Đứng Dậy Đi',
  publisher: 'ĐỨNG DẬY ĐI Channel',
  lang: 'vi',
  inputType: 'markdown',
  decorationStyle: 'noir',

  /** Where generated chapters live: {outputDir}/{ebookId}/chapters/*.md */
  knowledgeDir: KNOWLEDGE_DIR,

  themes: {
    free: { primary: '#B71C1C', accent: '#D32F2F', light: '#FFEBEE', gradient: 'linear-gradient(135deg, #1a0000 0%, #3e0000 50%, #B71C1C 100%)' },
    paid: { primary: '#0D47A1', accent: '#1565C0', light: '#E3F2FD', gradient: 'linear-gradient(135deg, #001a3e 0%, #0a2a5e 50%, #0D47A1 100%)' },
    premium: { primary: '#E65100', accent: '#EF6C00', light: '#FFF3E0', gradient: 'linear-gradient(135deg, #2e1400 0%, #4e2a00 50%, #E65100 100%)' },
  },

  imageStyle: {
    base: 'Dark cinematic realism style. MANDATORY SPLIT-FRAME DIPTYCH LAYOUT: the image MUST be clearly divided into TWO distinct visual panels side by side (left panel vs right panel) with a sharp visible dividing line or crack between them. Left panel shows the NEGATIVE dark consequence of ignorance and inaction — suffering, decay, entrapment. Right panel shows the POSITIVE bright outcome of understanding and taking action — growth, freedom, transformation. The contrast must be dramatic and instantly readable. High-contrast chiaroscuro lighting like Caravaggio. Gritty urban textures — concrete, glass, steel, smoke. ABSOLUTELY NO TEXT ANYWHERE — no words, no letters, no labels, no captions, no titles, no watermarks, no UI elements, no writing of any kind in any language on the image. Highly detailed digital painting. Full scene illustration. Vietnamese characters with strong determined features. Cinematic widescreen 16:9 composition.',
    palette: {
      free: 'Crimson red and charcoal black dominant palette. Blood-red accents on deep noir background. Smoke and embers. Raw awakening tones.',
      paid: 'Deep electric blue and dark iron dominant palette. Cold steel-blue light cutting through shadows. Analytical, surgical precision tones.',
      premium: 'Burning gold and obsidian black dominant palette. Molten metal glow against absolute darkness. Forging fire and transformation tones.',
    },
    mood: 'Confrontational, raw truth, warrior awakening. LEFT side = HARMFUL consequences of ignorance and inaction — suffering, loss, stagnation. RIGHT side = BENEFICIAL transformation through understanding and action — growth, freedom, power. Vietnamese urban setting.',
  },

  /** Voice DNA — injected into AI content generation prompts */
  voiceSystem: `Bạn là tác giả của kênh "ĐỨNG DẬY ĐI".
Giọng văn: Triết gia bóng tối với trái tim chiến binh.
Nghiêm túc nhưng không khô khan. Phũ phàng nhưng không tàn nhẫn.
Dùng ngôn ngữ chiến tranh và sinh tồn để giải phẫu mọi thứ — từ tiền bạc đến tâm lý.
Kết bằng tough love: "Đứng dậy đi, không ai cứu bạn ngoài chính bạn."

Quy tắc viết:
- Câu dài cuốn hút (30-50 từ) → tạo momentum như sóng biển
- Câu ngắn đóng đinh (3-8 từ) → impact, pause
- Câu trung chuyển tiếp (15-20 từ) → bridge sang ý tiếp
- Dùng ẩn dụ mạnh, ví dụ Việt Nam cụ thể
- Mỗi chương phải có hook mở đầu gây sốc
- Kết chương bằng tough love + gợi mở chương tiếp
- Viết bằng tiếng Việt, thuật ngữ chuyên môn giữ nguyên tiếng Anh`,

  /** TOC part grouping by chapter ID prefix */
  tocParts: {
    'p1-': 'PHẦN I — TÀI CHÍNH',
    'p2-': 'PHẦN II — TÂM LÝ',
    'p3-': 'PHẦN III — THUYẾT PHỤC',
    'p4-': 'PHẦN IV — KINH DOANH',
    'p5-': 'PHẦN V — KỶ LUẬT',
    'p6-': 'PHẦN VI — CẢM XÚC',
  },

  // ─── Ebook Definitions ──────────────────────────────────────
  ebooks: [
    {
      id: 'ebook-1-free',
      tier: 'free',
      title: 'Những Sự Thật Mà Cuộc Sống Đã Giấu Bạn',
      subtitle: 'Bước đầu tiên trên hành trình Đứng Dậy',
      tagline: 'Ebook miễn phí — tóm tắt hấp dẫn, hook mạnh, lôi cuốn người đọc',
      chapters: [
        { id: 'ch1', title: 'Bạn Đang Bị Lừa Về Tiền' },
        { id: 'ch2', title: 'Não Bạn Đang Phản Bội Bạn' },
        { id: 'ch3', title: '6 Vũ Khí Thao Túng Bạn Mỗi Ngày' },
        { id: 'ch4', title: 'Tại Sao Kỷ Luật Đánh Bại Động Lực' },
        { id: 'ch5', title: 'EQ — Siêu Năng Lực Bị Bỏ Quên' },
        { id: 'ch6', title: 'Sự Thật Về Khởi Nghiệp' },
        { id: 'ch7', title: 'Lời Kết — Đứng Dậy Đi' },
      ],
    },
    {
      id: 'ebook-2-paid',
      tier: 'paid',
      title: 'Giải Phẫu Sự Thật — Từ Tiền Bạc Đến Tâm Trí',
      subtitle: 'Deep-dive vào 28 cuốn sách & 815 video',
      tagline: 'Ebook trả phí — chi tiết, framework, case study, đáng đồng tiền',
      chapters: [
        { id: 'p1-ch1', title: 'Công Thức Wealth — NECST & Fastlane' },
        { id: 'p1-ch2', title: 'Nguyên Tắc Đầu Tư Bất Biến' },
        { id: 'p1-ch3', title: 'Lãi Kép & Đa Dạng Hóa — Vũ Khí Thời Gian' },
        { id: 'p1-ch4', title: 'Tâm Lý Tiền — Khi Cảm Xúc Điều Khiển Ví' },
        { id: 'p2-ch5', title: 'Hệ Thống Thiên Kiến — 12 Bẫy Tâm Lý Chi Tiết' },
        { id: 'p2-ch6', title: 'Kiến Trúc Quyết Định — Nudge & Framing' },
        { id: 'p2-ch7', title: 'Hạnh Phúc Thực Sự — Nghịch Lý & Khoa Học' },
        { id: 'p3-ch8', title: '6 Vũ Khí Cialdini — Phân Tích Sâu' },
        { id: 'p3-ch9', title: 'Hook Model & Thiết Kế Hành Vi' },
        { id: 'p4-ch10', title: 'Zero to One — Tạo vs Copy' },
        { id: 'p4-ch11', title: 'E-Myth & Build-Measure-Learn' },
        { id: 'p4-ch12', title: 'Crossing the Chasm & Chiến Lược D-Day' },
        { id: 'p5-ch13', title: 'Deep Work — Kỷ Luật Chiều Sâu' },
        { id: 'p5-ch14', title: '21 Nguyên Tắc Kỷ Luật Tối Thượng' },
        { id: 'p6-ch15', title: 'EQ Advanced — DISC & Metamood' },
        { id: 'p6-ch16', title: 'Lời Kết — Giải Phẫu Hoàn Tất' },
      ],
    },
    {
      id: 'ebook-3-premium',
      tier: 'premium',
      title: 'Bản Thiết Kế Cuộc Đời — 90 Ngày Đứng Dậy',
      subtitle: 'Chương trình hành động hoàn chỉnh',
      tagline: 'Ebook premium — hệ thống 90 ngày phát triển toàn diện',
      chapters: [
        { id: 'intro', title: 'Khởi Đầu — Bản Thiết Kế Của Bạn' },
        { id: 'm1', title: 'Module 1: Tự Đánh Giá Toàn Diện' },
        { id: 'm2', title: 'Module 2: Nền Tảng Tài Chính' },
        { id: 'm3', title: 'Module 3: Giải Phóng Tâm Lý' },
        { id: 'm4', title: 'Module 4: Hệ Thống Kỷ Luật' },
        { id: 'm5', title: 'Module 5: Nghệ Thuật Ảnh Hưởng' },
        { id: 'm6', title: 'Module 6: EQ Mastery' },
        { id: 'm7', title: 'Module 7: Tổng Kết & Lộ Trình 5 Năm' },
        { id: 'bonus', title: 'Bonus: Arsenal — Kho Vũ Khí' },
      ],
    },
  ],

  // ─── Chapter Image Prompts (by ID) ──────────────────────────
  chapterImages: {
    'ebook-1-free': [
      { id: 'ch1', prompt: 'Split composition: LEFT side — a Vietnamese office worker in a golden hamster wheel made of glowing credit cards, spinning endlessly in a dark void, face exhausted but smiling mechanically. RIGHT side — the same person breaking free, smashing through the wheel, fragments of cards flying like shattered glass, stepping onto a path of ember-lit stepping stones. Crimson fire illuminates the breaking point. Chains dissolving into smoke.' },
      { id: 'ch2', prompt: 'A Vietnamese man sitting on a throne made of a giant human brain, but the brain is cracked open revealing gears and puppet strings inside. His own hands are secretly pulling strings attached to his own limbs without him knowing. One half of the brain glows with deceptive golden light (System 1 illusions), the other half is dark and dormant (System 2 asleep). Crimson fog. Surreal anatomical noir.' },
      { id: 'ch3', prompt: 'A Vietnamese woman walking through a neon-lit Saigon street at night. Six massive invisible puppet masters loom above her in shadow — each representing a weapon of influence (reciprocity, scarcity, authority, social proof, liking, commitment). Their strings are attached to her wallet, phone, and heart. She is about to look up and SEE them. Red neon glow cutting through dark mist. Cyberpunk noir meets psychological thriller.' },
      { id: 'ch4', prompt: 'Split vertical: LEFT — a Vietnamese person surrounded by floating phone notifications, coffee cups, half-finished tasks, shallow scattered light, chaos and fragmentation, face anxious. RIGHT — the same person in deep focus at a single clean desk, single powerful spotlight from above, phone locked away, deep concentrated expression. The boundary between chaos and focus is a sharp blade of crimson light cutting the scene in half.' },
      { id: 'ch5', prompt: 'A Vietnamese woman standing in front of a massive glowing emotional control panel inside her own chest cavity (visible like an X-ray). The panel has 5 glowing dials: Self-Awareness (gold), Self-Management (blue), Motivation (red), Empathy (green), Social Skills (white). Her hand reaches to adjust the dials. Behind her, a shadow version of herself is consumed by emotional chaos — fire, tears, rage. Anatomical surrealism meets noir. Crimson amygdala glowing in the brain above.' },
      { id: 'ch6', prompt: 'A Vietnamese young entrepreneur standing at a crossroads in a dark industrial cityscape. One path shows a glowing copycat factory mass-producing identical products (1→n, comfortable but dim). The other path is a narrow dangerous bridge over a chasm of fire leading to a single brilliant lighthouse (0→1, terrifying but purposeful). The entrepreneur holds a blueprint that glows with crimson light. Dark rain. Industrial noir.' },
      { id: 'ch7', prompt: 'A lone Vietnamese figure standing on the edge of a crumbling cliff at dawn. Behind them, the dark ruined landscape of old beliefs, broken chains, shattered mirrors, extinguished puppet strings. Ahead, a vast open crimson sunrise horizon with a single narrow path forward. The figure is battered but standing tall, fists clenched, looking forward. Wind blowing their hair. Epic warrior stance. Triumph through damage. Cinematic wide shot.' },
      { id: 'ch1-mid', prompt: 'Split diptych: LEFT (HARMFUL) — Vietnamese person trapped in Sidewalk lifestyle, drowning in credit card debt, flashy motorbike on installment, eating convenience store meals alone, stressed face staring at overdue bills under harsh fluorescent light, dark cramped rental room, financial slavery. RIGHT (BENEFICIAL) — Same person on Fastlane path, building a laptop-based business system, multiple income streams flowing as golden rivers on a glowing blueprint, calm confident expression, sunrise through a clean modern window, financial freedom achieved young.' },
      { id: 'ch2-mid', prompt: 'Split diptych: LEFT (HARMFUL) — Vietnamese person controlled by System 1 autopilot thinking, impulse-buying during Shopee flash sale frenzy, phone screen hypnotizing them with red discount tags, brain shown as tangled mess of cognitive bias shortcuts, anchoring chains and confirmation bubbles trapping their judgment. RIGHT (BENEFICIAL) — Same person with System 2 activated, X-ray analytical vision seeing through every marketing trick, brain shown as clear organized control panel with bias-detectors, calmly analyzing data, making rational calculated decisions.' },
      { id: 'ch3-mid', prompt: 'Split diptych: LEFT (HARMFUL) — Vietnamese consumer as marionette puppet with 6 visible manipulation strings (reciprocity, scarcity, authority, social proof, liking, commitment) pulling them toward their wallet, zombie-like shopping expression, surrounded by KOL ads and flash sale banners in overwhelming neon market. RIGHT (BENEFICIAL) — Same person who has CUT all 6 strings with golden scissors, standing tall and aware, now HOLDING those 6 weapons as golden tools of ethical influence and leadership, teaching others, radiating awareness and power.' },
      { id: 'ch4-mid', prompt: 'Split diptych: LEFT (HARMFUL) — Vietnamese person on a motivation rollercoaster — excited January with new gym membership and fresh planners, crashed by February surrounded by abandoned equipment and half-read books, motivation graph plummeting to zero, distraction chaos everywhere, years wasted in cycles. RIGHT (BENEFICIAL) — Same person with iron discipline system — Pomodoro timer ticking perfectly, clean minimalist desk with single deep task, progress blocks stacking steadily like an unbreakable tower, routine calendar glowing with consistency, calm powerful mastery expression.' },
      { id: 'ch5-mid', prompt: 'Split diptych: LEFT (HARMFUL) — Vietnamese person in emotional hijacking mode, amygdala literally on fire controlling their actions, screaming at colleague in office, panic-selling stocks on phone showing red charts, broken relationship frames scattered around, face contorted with rage and instant regret, completely isolated. RIGHT (BENEFICIAL) — Same person with EQ mastery, 4 DISC harmony colors (red/yellow/green/blue) radiating from their calm centered chest, empathetically listening to a friend, emotional dashboard showing all 5 Goleman dials in optimal green zone, surrounded by strong loving connections.' },
      { id: 'ch6-mid', prompt: 'Split diptych: LEFT (HARMFUL) — Vietnamese entrepreneur in E-Myth trap, talented cook drowning alone in their own restaurant kitchen — cooking serving cleaning accounting all by themselves, haggard exhausted face aging rapidly, closing-down sign looming overhead, chaos smoke and debt. RIGHT (BENEFICIAL) — Same person as system-building CEO, watching a well-oiled business machine run perfectly from outside through glass walls, trained team executing flawlessly, holding expansion blueprints for second branch, calm visionary expression, freedom achieved.' },
      { id: 'ch7-mid', prompt: 'Split diptych: LEFT (HARMFUL) — Vietnamese person sitting in comfortable ignorance, cozy but tiny room with TV showing shallow entertainment, never growing or questioning, same routine for decades, invisible prison bars casting long shadows on the wall, aging face filled with deep what-if regret and unfulfilled potential. RIGHT (BENEFICIAL) — Same person who faced every hard truth in this book, now standing in vast open landscape of endless possibility, battle scars of growth worn proudly, wind in their hair, carrying tools of knowledge and wisdom, radiating unstoppable purpose and total freedom.' },
    ],
    'ebook-2-paid': [
      { id: 'p1-ch1', prompt: 'A Vietnamese figure dissecting a giant golden coin on a surgical steel table under cold blue operating lights. Inside the coin reveals intricate machinery — three pathways (Sidewalk, Slowlane, Fastlane) as mechanical tracks. The surgeon wears dark scrubs and holds a scalpel that glows electric blue. X-ray displays on screens behind showing wealth formulas. Clinical precision. Surgical noir. Steel blue palette.' },
      { id: 'p1-ch2', prompt: 'Split composition: LEFT — Vietnamese investors in panic, red stock charts raining down like broken glass, FOMO fire burning stacks of money. RIGHT — a calm figure sitting on a fortress of books (Graham, Marks, Lynch), looking through a magnifying glass at the same chaos, but seeing PATTERNS and VALUE beneath. Cold blue analytical light vs chaotic red fire. Investment battlefield noir.' },
      { id: 'p1-ch4', prompt: 'Two Vietnamese figures standing side by side but in completely different worlds. LEFT: Rajat Gupta type — suited, powerful, golden tower crumbling beneath him into prison bars. RIGHT: Ronald Read type — humble uniform, tiny apartment, but standing on an invisible mountain of compound interest rendered as blue glowing exponential curve. The contrast of visible wealth vs invisible wealth. Dual portrait noir.' },
      { id: 'p2-ch5', prompt: 'A Vietnamese person trapped inside a massive glass brain filled with 12 floating dark orbs, each containing a different cognitive bias visualized as a miniature scene (anchor, bandwagon, confirmation, etc). The person pushes against the glass trying to escape while the orbs orbit around them hypnotically. One crack appears in the glass where they push hardest. Electric blue light leaking through the crack. Psychological prison noir.' },
      { id: 'p2-ch6', prompt: 'A Vietnamese woman on a tightrope between two skyscrapers in a storm. On one building: FOMO written in burning letters with a crowd leaping off (herd mentality). On the other building: RATIONAL DECISION with a single glowing doorway. She balances carefully, wind and rain lashing her. Below is a void of lost money and broken charts. The tightrope is made of cold blue light. Vertigo noir.' },
      { id: 'p3-ch8', prompt: 'Six massive stone chess pieces on a dark chessboard, each carved as one of Cialdini\'s 6 weapons (crown for authority, mirror for liking, hourglass for scarcity, chain for commitment, crowd for social proof, gift for reciprocity). A lone Vietnamese figure walks between them, small but aware, studying each piece with a tactical flashlight that cuts through darkness. Strategic dissection. Electric blue beam. War room noir.' },
      { id: 'p3-ch9', prompt: 'Aerial view of a Vietnamese city crowd moving in unison like a massive school of fish, directed by invisible algorithmic waves emanating from giant smartphone screens that tower over the city like monoliths. One person in the center has stopped moving, looking up, seeing the manipulation pattern from a different angle, glowing blue aura around them. The Hook Model visualized as fishing hooks in the digital waves. Surveillance noir. Dystopian blue palette.' },
      { id: 'p4-ch10', prompt: 'A Vietnamese inventor in a dark workshop, welding sparks flying. They are building something that has NEVER existed before — a strange glowing machine made of ideas, code, and fire. Through the window, a factory district mass-produces identical boxes (1→n copycat world). Their unique creation glows with intense electric blue against the industrial darkness. Lone creator vs mass production. Industrial maker noir.' },
      { id: 'p4-ch11', prompt: 'Split: LEFT — a Vietnamese restaurant owner drowning in their own kitchen, doing everything themselves — cooking, serving, cleaning, accounting — face exhausted, surrounded by chaos and flames. RIGHT — the SAME person standing outside a glass building, watching a well-oiled machine run perfectly without them, blueprints in hand, calm expression. The E-Myth transformation. System builder vs technician trap. Blue architectural light.' },
      { id: 'p5-ch13', prompt: 'A Vietnamese figure in deep meditative focus inside a sphere of absolute silence and blue light, while outside the sphere a hurricane of notifications, messages, social media logos, news headlines rages violently. The sphere is cracking under pressure but holding. Inside: calm, singular focus, one important task. Outside: shallow work chaos. Deep Work fortress noir. Cold blue focus vs warm chaotic noise.' },
      { id: 'p5-ch14', prompt: 'A Vietnamese warrior figure forging a sword on an anvil, but the sword is labeled DISCIPLINE and the hammer strikes create sparks that form daily habits — Pomodoro timers, 4AM wake-up, checklist items. Each hammer blow is perfectly rhythmic. In the background, broken swords labeled MOTIVATION litter the ground, abandoned and rusted. Discipline over motivation. Forge and fire noir. Blue steel sparks.' },
      { id: 'p6-ch15', prompt: 'A Vietnamese person sitting at the center of a four-color compass rose — Red (Dominant), Yellow (Influence), Green (Stability), Blue (Compliance) — each quadrant showing different communication styles as ghostly figures. The central person has all four colors swirling in their awareness, eyes glowing with understanding. Behind them, an EQ meter dial turns from "reactive" to "mastered". Emotional intelligence dashboard. Analytical color theory noir.' },
      { id: 'p6-ch16', prompt: 'A Vietnamese figure standing before a massive open door in a dark corridor. Through the door: blinding golden light of actionable truth. Behind them: 6 rooms they\'ve passed through (Finance, Psychology, Persuasion, Business, Discipline, Emotion) — each room\'s door still glowing with its lesson. They carry dissection tools now transformed into building tools. The surgery is done — now rebuild. Transformation corridor. Blue to gold gradient. Noir to dawn.' },
    ],
    'ebook-3-premium': [
      { id: 'intro', prompt: 'A Vietnamese architect standing before a massive blank dark wall, holding a glowing golden blueprint pen. As they draw, the lines come alive — glowing golden architectural plans for a LIFE: career paths, relationship networks, financial flows, all interconnected like circuit boards. Behind them, crumpled old blueprints litter the ground (old failed plans). Fresh start energy. Obsidian darkness and molten gold lines. Architect of fate noir.' },
      { id: 'm1', prompt: 'A Vietnamese person looking into a massive dark mirror, but the reflection shows their TRUE self — strengths, weaknesses, fears, hidden talents — all visualized as golden glowing anatomical layers peeling back. The outer shell is cracked and honest. Assessment tools float around like golden holographic displays (EQ dial, DISC compass, financial dashboard, discipline wheel). Self-dissection before transformation. Obsidian mirror noir. Gold revelation light.' },
      { id: 'm2', prompt: 'A Vietnamese person building a financial fortress from the ground up — laying bricks of golden coins, each brick labeled (Emergency Fund, ETF, Compound Interest, Budget). Some old broken structures (debt, impulse spending) smolder nearby. A 7-year roadmap glows as a golden holographic timeline above. Construction site noir. Obsidian ground, molten gold building materials. Foundational strength.' },
      { id: 'm3', prompt: 'A Vietnamese figure wearing neural-interface goggles, navigating through a dark maze made of 12 cognitive biases visualized as trap doors, illusion mirrors, and false exits. Their golden flashlight reveals the true path. A "Mental Model Map" glows as a golden holographic compass in their hand. Debiasing journey through the mind. Dark labyrinth noir. Gold truth-light cutting through deception.' },
      { id: 'm4', prompt: 'A Vietnamese warrior-monk in pre-dawn darkness, performing a precise ritual: deep work station perfectly arranged, Pomodoro timer counting, phone locked in a box, single candle-like golden light. Split with a ghostly version of themselves scattered across 20 shallow tasks in chaotic daylight. The disciplined version radiates quiet power. Ritual of depth. Monastery meets industrial noir. Gold candlelight vs scattered white noise.' },
      { id: 'm5', prompt: 'A Vietnamese leader standing on a dark stage, conducting an invisible orchestra of influence. Six golden orbs (Cialdini weapons) orbit around their raised hands, controlled and purposeful. In the audience, people are moved not by manipulation but by genuine leadership. OKR framework glows as a golden scoreboard. From being manipulated TO wielding influence ethically. Dark theater noir. Spotlight gold.' },
      { id: 'm6', prompt: 'A Vietnamese person in a dark meditation chamber, slowly building a golden neural network inside their chest — each connection is an emotional skill: empathy, self-regulation, social awareness. The 30-day training visualized as golden rings forming layers of emotional armor. DISC colors (red, yellow, green, blue) glow at the edges. EQ training montage in a single frame. Internal alchemy noir. Gold network light.' },
      { id: 'm7', prompt: 'A Vietnamese figure standing atop a dark mountain peak at the golden hour of transformation. They hold a 5-year master blueprint that unfurls like a golden scroll into the horizon. Below, the 90-day journey is visible — 7 base camps (modules) glowing golden along the mountain path. The view is vast, powerful, earned. Destination reached but journey continues. Summit noir. Obsidian mountain, molten gold sunrise. Epic wide shot.' },
      { id: 'bonus', prompt: 'An elegant dark war room table from above — golden scrolls of Viral Hooks, a glowing Mental Model Map as a holographic sphere, 28 miniature book icons arranged in formation, framework templates stacked neatly. A single golden pen rests at the center. Everything organized for warfare and mastery. Arsenal noir. Top-down view. Obsidian table, gold tactical elements.' },
    ],
  },

  // ─── Cover Image Prompts ────────────────────────────────────
  coverImages: {
    'ebook-1-free': {
      cover: 'A breathtaking cinematic book cover. A lone Vietnamese figure stands at the center of a massive cracked mirror in an abandoned dark cathedral. Through the cracks, crimson light bleeds outward revealing hidden truths. The figure\'s silhouette is half-shrouded in shadow (illusion side) and half-illuminated by harsh red light (truth side). Shattered glass fragments float in the air. Dramatic vertical composition. Cathedral noir grandeur. Crimson and charcoal. Professional book cover quality.',
      intro: 'A Vietnamese person sitting alone in a dark empty room, the only light source is a single crimson match they just struck, held up close to their face, illuminating truth in their eyes. Long shadows stretch across concrete walls covered in faded propaganda-style posters about money, success, happiness — all cracking and peeling. First spark of awakening. Intimate noir. Crimson matchlight.',
    },
    'ebook-2-paid': {
      cover: 'A breathtaking cinematic book cover. A Vietnamese surgeon-scholar stands in a dark operating theater, scalpel raised, about to dissect a massive glowing blue brain that floats above a steel surgical table. The brain shows visible sections: Finance, Psychology, Persuasion, Business, Discipline, Emotion — each glowing different shade of electric blue. X-ray screens line the walls. Dramatic vertical composition. Surgical precision noir. Deep electric blue on dark iron. Professional book cover quality.',
      intro: 'Overhead view of a dark dissection table with 6 labeled specimen jars, each containing a glowing blue essence: one has gears (Finance), one has an eye (Psychology), one has puppet strings (Persuasion), one has a blueprint (Business), one has a sword (Discipline), one has a heart (Emotion). Surgical tools arranged precisely. Clinical analytical. Electric blue glow on dark steel. Specimen noir.',
    },
    'ebook-3-premium': {
      cover: 'A breathtaking cinematic book cover. A Vietnamese architect-warrior stands on the edge of a dark precipice, arms extended, holding a massive glowing golden blueprint that unfurls into the void. The blueprint\'s golden lines come alive — forming buildings, bridges, pathways, neural networks — all glowing intensely against absolute obsidian darkness. Below, the abyss. Above, a single golden sun breaking through storm clouds. Dramatic vertical composition. Architect of destiny noir. Burning gold on obsidian. Professional book cover quality.',
      intro: 'A Vietnamese person\'s open hands in close-up, palms up, in near darkness. In their left palm: a small crumbling dark model of their OLD life. In their right palm: a glowing golden seed with golden root tendrils growing out. The gold light from the seed illuminates their determined face from below. Rebirth in their hands. Intimate transformation. Golden seed noir.',
    },
  },

  // ─── Intro Quotes ───────────────────────────────────────────
  introQuotes: {
    'ebook-1-free': {
      text: 'Sự thật không giết bạn.\nChính những lời nói dối ngọt ngào\nmới đang giết bạn từng ngày.',
      attribution: '— ĐỨNG DẬY ĐI —',
    },
    'ebook-2-paid': {
      text: 'Muốn chữa bệnh,\ntrước hết phải dám mổ xẻ.\nKhông có phẫu thuật nào không đau.',
      attribution: '— ĐỨNG DẬY ĐI —',
    },
    'ebook-3-premium': {
      text: 'Bạn không sinh ra để sống\ncuộc đời người khác thiết kế.\nĐứng dậy đi. Vẽ bản thiết kế của riêng bạn.',
      attribution: '— ĐỨNG DẬY ĐI —',
    },
  },
};
